### PR TITLE
add php 5.6 to travis

### PR DESCRIPTION
**Pull request by saeideng**
add missed php 5.6 to travis

### CODE REVIEW

**Comment by dereuromark** [comment]
Already covered with PREFER_LOWEST=1

**Comment by saeideng** [comment]
>Already covered with PREFER_LOWEST=1

no
`PREFER_LOWEST` uses lowest vendors if possible 
but this use latest version of vendors

**Comment by dereuromark** [comment]
Well, if you feel strongly about it, we can sure re-add.

**Comment by saeideng** [comment]
thanks

**Pull request merged**
