### PR TITLE
Update default cache name based on CakePHP 5.1.0 Application Skeleton

### PR DESCRIPTION
**Pull request by MarksSoftwareGmbH**
https://github.com/cakephp/app/blob/61995e160bb4fbd38a744a53576b827227bda0f8/config/app.php#L112

### CODE REVIEW

**Comment by dereuromark** [comment]
For some reason the tests fail

**Comment by MarksSoftwareGmbH** [comment]
> For some reason the tests fail

Correct, after creating a new cakephp/app based on the latest skeleton and installing tinyauth the app runs into the non existent "_cake_translations_" cache configuration.

`[Cake\Cache\Exception\InvalidArgumentException] The `_cake_core_` cache configuration does not exist.`

You are right the test failed.

**Comment by MarksSoftwareGmbH** [comment]
> Maybe we shouldn't use translations key _cake_model_ seems more appropriate

I will solve this issue by updating the latest [cakephp/app app.php Cache Config array](https://github.com/cakephp/app/blob/61995e160bb4fbd38a744a53576b827227bda0f8/config/app.php#L97) with '_cake_core_' and  '_cake_translations_'

`'_cake_translations_' => [
            'className' => FileEngine::class,
            'prefix' => 'myapp_cake_translations_',
            'path' => CACHE . 'persistent' . DS,
            'serialize' => true,
            'duration' => '+1 years',
            'url' => env('CACHE_CAKECORE_URL', null),
        ],

'_cake_core_' => [
            'className' => FileEngine::class,
            'prefix' => 'myapp_cake_core_',
            'path' => CACHE . 'persistent' . DS,
            'serialize' => true,
            'duration' => '+1 years',
            'url' => env('CACHE_CAKECORE_URL', null),
        ]`

**Comment by MarksSoftwareGmbH** [comment]
> What do you think about this one? [9780aa0](https://github.com/dereuromark/cakephp-tinyauth/commit/9780aa082f2f56e9dffc0b1cc9181ac495348da7)

You wrote, what I thought about a few min ago, to capsule / check for the old config name. thank you.

**Pull request merged**
