### PR TITLE
AuthUser::hasAccess()

### PR DESCRIPTION
**Pull request by saeideng**
Refs : https://github.com/dereuromark/cakephp-tinyauth/pull/101

throw MissingRouteException when url is incomplete

### CODE REVIEW

**Comment by dereuromark** [comment]
Should this only be done in debug mode? This seems to cost Performance.

**Comment by saeideng** [comment]
>Should this only be done in debug mode?

no
we have to throw exception when a needed route elements  `{var}` is missing
I removed unnecessary  `if/else` because code handles by `Router::url()`

**Comment by dereuromark** [comment]
Why is this needed? The result is still the same. 
We dont care here for other cases either. Mainly as this is expensive for many checks on one page.
Only in debug mode it could be useful to know you made a mistake.

**Comment by saeideng** [comment]
>Mainly as this is expensive for many checks on one page.

which part ? `Router::url($url);` ?

**Comment by dereuromark** [comment]
Yes, especially when called often.

**Comment by saeideng** [comment]
if you think no different between `post/view/1` and `post/view`
you can ignore this PR :)

**Comment by dereuromark** [comment]
Those both return false if invalid right,

**Comment by saeideng** [comment]
when you connect `post/view/{id}` in routes, and you want check access to `post/view`(with applying `_name`)
1)with this PR, throws a exception
2)without this PR, returns true

**Comment by saeideng** [comment]
@dereuromark could we cache the result or it is not possible ?

**Pull request merged**
