### PR TITLE
Fixes Cake 3.x multirole authorization

### PR DESCRIPTION
**Pull request by bravo-kernel**
Fixes:

- fetching available roles from database
- fetching user's associated roles

Open:

- should user's associated roles be cached or is the query fast enough?
- test using Model
- fix broken tests

### CODE REVIEW

**Comment by bravo-kernel** [comment]
I would suggest changing the `aclKey` and `aclTable` to `roleColumn` and `roleTable` to keep the naming more in line with the code (and what they are used for).

**Comment by dereuromark** [comment]
Cool.
Do we need some new tests?

Renaming these keys is fine with me.

**Comment by bravo-kernel** [comment]
We do need some new tests but I would prefer to consult on how to continue first. Going through this part is see there is logic that is either no longer applicable or was intended to be used otherwise.

**Comment by bravo-kernel** [comment]
Now supports 3 scenarios:

- single-role with available roles using Configure array
- single-role with availble roles using database table
- multirole (requires database table and join table)

Tests need updating

**Comment by dereuromark** [comment]
IMO it should support both single and multi role with either DB or Configure.
They way they are retrieved shouldn't matter IMO, as it didnt before.
Is there a specific issue why that cannot be supported this way in your opinion?

**Comment by bravo-kernel** [comment]
I'm not 100% sure but I don't think multirole using only Configure worked before, maybe we should discuss this to prevent miscommunication.

**Comment by dereuromark** [comment]
It must have worked before, especially in 2.x :)
At least I thought I used it in one app. But no big deal either way.
We should just try to make it work in a way that the actual source is irrelevant (maybe even cached at some point then in the future) as it will just work with both ways the same way.

**Comment by bravo-kernel** [comment]
Let's discuss on IRC when you have the time, it might be my lack of understanding.

**Comment by bravo-kernel** [comment]
Looks good to me.

**Comment by bravo-kernel** [comment]
Ty for merging :)

**Pull request merged**
